# Generated by Django 3.2 on 2021-04-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0009_transactions_newbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycard',
            name='recover',
            field=models.IntegerField(default=0),
        ),
    ]
